name: buildx
on:
  pull_request:
    types: [closed]
    branches: master
  push:
    branches: master
  workflow_dispatch: []

jobs:
  build-nsfwjs:
    runs-on: [ubuntu-20.04]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
      - 
        name: Setup node
        uses: actions/setup-node@v2.1.3
        with:
          node-version: '10'
      - 
        name: Set env
        run: echo "CI=false" >> $GITHUB_ENV
      - 
        name: Build nsfwjs release
        run: |
          yarn prep 
          cd example/nsfw_demo
          yarn install 
          yarn build
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v3
        with:
          images: |
            suika/nsfwjs
            ghcr.io/suika/nsfwjs
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: "--debug"
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: suika/nsfwjs:latest,ghcr.io/suika/nsfwjs:latest
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6
          labels: |
            ${{ steps.docker_meta.outputs.labels }}
            org.opencontainers.image.title=NSFWJS
            org.opencontainers.image.vendor=suika
      -
        name: Check manifest
        run: |
          docker buildx imagetools inspect suika/nsfwjs:latest
          docker buildx imagetools inspect ghcr.io/suika/nsfwjs:latest
      -
        name: Inspect image
        run: |
          docker pull suika/nsfwjs:latest
          docker image inspect suika/nsfwjs:latest
          docker pull ghcr.io/suika/nsfwjs:latest
          docker image inspect ghcr.io/suika/nsfwjs:latest
